# Generated by Django 2.1.1 on 2018-09-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pick1', models.CharField(max_length=50)),
                ('pick2', models.CharField(max_length=50)),
                ('pick3', models.CharField(max_length=50)),
                ('pick4', models.CharField(max_length=50)),
                ('pick5', models.CharField(max_length=50)),
                ('pick6', models.CharField(max_length=50)),
                ('pick7', models.CharField(max_length=50)),
                ('pick8', models.CharField(max_length=50)),
                ('pick9', models.CharField(max_length=50)),
                ('pick10', models.CharField(max_length=50)),
                ('pick11', models.CharField(max_length=50)),
                ('pick12', models.CharField(max_length=50)),
                ('pick13', models.CharField(max_length=50)),
                ('pick14', models.CharField(max_length=50)),
                ('pick15', models.CharField(max_length=50)),
                ('pick16', models.CharField(max_length=50)),
                ('totalPtsMonday', models.IntegerField()),
                ('totalCorrect', models.IntegerField()),
                ('submission_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
