# Generated by Django 2.1.1 on 2018-09-23 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyPicks', '0002_auto_20180921_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='picks',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pick', to='weeklyPicks.Pick'),
        ),
    ]
