# Generated by Django 2.1.1 on 2018-09-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyPicks', '0003_auto_20180923_0620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picks',
        ),
        migrations.AddField(
            model_name='user',
            name='picks',
            field=models.ManyToManyField(blank=True, related_name='pick', to='weeklyPicks.Pick'),
        ),
    ]
