# Generated by Django 2.1.1 on 2018-09-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyPicks', '0004_auto_20180923_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picks',
        ),
        migrations.AddField(
            model_name='pick',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to='weeklyPicks.User'),
        ),
    ]
