# Generated by Django 2.1.1 on 2018-09-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyPicks', '0005_auto_20180923_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pick',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user', to='weeklyPicks.User'),
        ),
    ]
